<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="unittest.loader._FailedTest-20180925110341" skipped="0" tests="1" time="0.000" timestamp="2018-09-25T11:03:41">
	<testcase classname="unittest.loader._FailedTest" name="test_basics" time="0.000" timestamp="2018-09-25T11:03:41">
		<error message="Failed to import test module: test_basics
Traceback (most recent call last):
  File &quot;/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py&quot;, line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File &quot;/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py&quot;, line 375, in _get_module_from_name
    __import__(name)
  File &quot;/Users/levlaz/git/SupportService/tests/test_basics.py&quot;, line 5, in &lt;module&gt;
    from app.factory import create_app, db
  File &quot;/Users/levlaz/git/SupportService/app/factory.py&quot;, line 10, in &lt;module&gt;
    from app.config import config
  File &quot;/Users/levlaz/git/SupportService/app/config.py&quot;, line 8
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or
                                                               ^
SyntaxError: invalid syntax
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: test_basics
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/Users/levlaz/git/SupportService/tests/test_basics.py", line 5, in <module>
    from app.factory import create_app, db
  File "/Users/levlaz/git/SupportService/app/factory.py", line 10, in <module>
    from app.config import config
  File "/Users/levlaz/git/SupportService/app/config.py", line 8
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or
                                                               ^
SyntaxError: invalid syntax

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
